Internet_Market/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('', include('main.urls', namespace='home')),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),

]

cart/urls.py
from django.urls import path, re_path
from cart import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_details, name='details'),
    path('add/', views.cart_add, name='add'),
    path('remove/<int:id>/', views.cart_remove, name='remove'),
    # path('clear/', views.cart_remove_all, name='clear'),
    path('show/', views.cart_show, name='show'),
    path('add-single/', views.add_single, name='add-single'),
]

main/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from . import views

app_name = 'main'
urlpatterns = [
    path('', views.home, name='home'),
    re_path(r'category/(?P<slug>[-\w]+)/', views.CategoryList.as_view(), name="category"),
    path('category/<slug:slug>/page/<int:page>', views.CategoryList.as_view(), name="category"),
    re_path(r'product/(?P<slug>[-\w]+)/(?P<id>\S+_[0-9]{3,})', views.ProductDetail, name="detail"),
    path('product/<slug:slug>-Code-<int:id>/', views.ProductDetail, name="detail"),
    re_path('like/(?P<id>[-\w]*)/$', views.product_like, name='product_like'),
    path('like/<int:id>/', views.product_like, name='product_like'),
    path('comment/<int:id>/', views.product_comment, name='comment'),
    path('replay/<int:id>/<int:comment_id>/', views.product_replay, name='replay'),
    re_path('favourite/(?P<id>[-\w]*)/$', views.favourite_product, name='favourite_product'),
    path('favourite/<int:id>/', views.favourite_product, name='favourite_product'),
    path('favourite/', views.favourite, name='favourite'),
    path('products/', views.Product_Side, name='side'),
    path('compare/<int:id>/',views.compare,name='compare'),
    path('compare/delete/<int:pk>/',views.Compare_del.as_view(),name='del'),
    path('compare/',views.show_compare,name='show'),
]
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# 👆👆👆👆 halat deploy👆👆👆👆

main/forms.py
from main.models import Comment, Compare
from django.forms import ModelForm


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ('comment',)


class ReplayForm(ModelForm):
    class Meta:
        model = Comment
        fields = ('comment','replay',)


class CompareForm(ModelForm):
    class Meta:
        model = Compare
        fields = ('product',)

main/views.py
from urllib.parse import urlencode
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Min, Max, Q,Count,Sum
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.urls import reverse_lazy
from django.views.generic import ListView, DeleteView
from main.filters import ProductFilter
from main.forms import CommentForm, ReplayForm
from cart.forms import CartAddForm
from main.models import *
from cart.cart import Cart
from django.http import JsonResponse





class CategoryList(ListView):
    paginate_by = 15
    template_name = 'main/category.html'

    def get_queryset(self):
        global category
        slug = self.kwargs.get('slug')
        category = get_object_or_404(Category, slug=slug)
        return Product.objects.published()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = category
        return context


def home(request, slug=None):
    products = Product.objects.published().order_by('-create')[:6]
    category = Category.objects.filter(available=True)
    if slug:
        category = get_object_or_404(Category, slug=slug)
    context = {'products': products, 'category': category, }

    return render(request, 'main/home.html', context)


# class SearchList(ListView):
#     paginate_by = 3
#     template_name = 'main/shop-sidebar.html'
#
#     def get_queryset(self):
#         search = self.request.GET.get('q')
#         return Product.objects.filter(Q(description__icontains=search) | Q(name__icontains=search))
#
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['search'] = self.request.GET.get('q')
#         return context

def Product_Side(request):
    products = Product.objects.published().order_by('-create')
    min = Product.objects.aggregate(unit_price=Min('unit_price'))
    min_price = int(min['unit_price'])
    max = Product.objects.aggregate(unit_price=Max('unit_price'))
    max_price = int(max['unit_price'])
    filter = ProductFilter(request.GET, queryset=products)
    products = filter.qs
    paginator = Paginator(products, 15)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    # search
    if 'search' in request.GET:
        search = request.GET['search']
        if search:
            page_obj = products.filter(
                Q(description__icontains=search) | Q(name__icontains=search))
    # category = Category.objects.filter(sub_cat=False)
    # if slug and id :
    # data = get_object_or_404(Category, slug=slug,pk=id)

    context = {'products': page_obj,
               'page_number': page_number,
               'filter': filter,
               'min_price': min_price,
               'max_price': max_price,
               'values': request.GET,
               }
    return render(request, 'main/shop-sidebar.html', context)


def ProductDetail(request, id, slug=None):
    product = get_object_or_404(Product, pk=id, slug=slug)
    if request.user.is_authenticated:
        product.view_count.add(request.user)
    update = Chart.objects.filter(product_id=id)
    updates = Chart.objects.all()
    images = PostImage.objects.filter(product_id=id)
    comment_form = CommentForm()
    replay_form = ReplayForm()
    cart_form = CartAddForm()
    comment = Comment.objects.filter(product_id=id, is_replay=False).order_by('-create')
    similar = product.tags.similar_objects()[:3]

    if request.method == "POST":
        variant = Variant.objects.filter(product_variant_id=id)
        var_id = request.POST.get('selected')
        variants = Variant.objects.get(id=var_id)
        colors = Variant.objects.filter(product_variant_id=id, size_variant_id=variants.size_variant_id)
        size = Variant.objects.raw(
            'SELECT * FROM main_variant WHERE product_variant_id=%s GROUP BY size_variant_id', [id])
        # size = Variant.objects.filter(product_variant_id=id).distinct('size_variant_id')
    else:
        variant = Variant.objects.filter(product_variant_id=id)
        variants = Variant.objects.get(id=variant[0].id)
        colors = Variant.objects.filter(product_variant_id=id, size_variant_id=variants.size_variant_id)
        size = Variant.objects.raw(
            'SELECT * FROM main_variant WHERE product_variant_id=%s GROUP BY size_variant_id', [id])
    context = {'product': product, 'images': images, 'comment_form': comment_form, 'replay_form': replay_form,
               'cart_form': cart_form, 'comment': comment, 'variant': variant, 'variants': variants, 'colors': colors,
               'size': size, 'update': update, 'updates': updates, 'similar': similar}
    return render(request, 'main/shop-details.html', context)


def product_like(request, id):
    url = request.META.get('HTTP_REFERER')
    product = get_object_or_404(Product, id=id)
    if product.like.filter(id=request.user.id).exists():
        product.like.remove(request.user)
    else:
        product.like.add(request.user)
        messages.success(request, 'با تشکر از لایک شما', 'success')
    # return redirect('main:detail', product.id)
    return redirect(url)


@login_required()
def product_comment(request, id):
    url = request.META.get('HTTP_REFERER')
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            data = comment_form.cleaned_data
            Comment.objects.create(comment=data['comment'], user_id=request.user.id, product_id=id)
    return redirect(url)


@login_required()
def product_replay(request, id, comment_id):
    url = request.META.get('HTTP_REFERER')
    if request.method == 'POST':
        replay_form = ReplayForm(request.POST)
        if replay_form.is_valid():
            data = replay_form.cleaned_data
            Comment.objects.create(comment=data['comment'], user_id=request.user.id, product_id=id,
                                   replay_id=comment_id, is_replay=True)
    return redirect(url)


@login_required()
def favourite_product(request, id):
    product = get_object_or_404(Product, id=id)
    if product.favourite.filter(id=request.user.id).exists():
        product.favourite.remove(request.user)
        product.total_favourite -= 1
        messages.warning(request, 'محصول از علاقه مندی ها حذف شد', 'warning')
    else:
        product.favourite.add(request.user)
        product.total_favourite += 1
        messages.success(request, 'محصول به علاقه مندی ها اضافه شد', 'success')
    product.save()
    data = {'success': 'ok'}
    return JsonResponse(data)


def favourite(request):
    product = request.user.fa_user.all()
    context = {'product': product}
    return render(request, 'main/shop.html', context)


def compare(request, id):
    url = request.META.get('HTTP_REFERER')
    if request.user.is_authenticated:
        item = get_object_or_404(Product, id=id)
        qs = Compare.objects.filter(user_id=request.user.id, product_id=id)
        if qs.exists():
            messages.success(request, 'محصول برای مقایسه کردن اضافه شد')
        else:
            Compare.objects.create(user_id=request.user.id, product_id=item.id, session_key=None)
            messages.success(request, 'محصول برای مقایسه کردن اضافه شد')

    else:
        item = get_object_or_404(Product, id=id)
        qs = Compare.objects.filter(user_id=None, product_id=id, session_key=request.session.session_key)
        if qs.exists():
            messages.success(request, 'محصول برای مقایسه کردن اضافه شد')
        else:
            if not request.session.session_key:
                request.session.create()
            Compare.objects.create(user_id=None, product_id=item.id, session_key=request.session.session_key)
            messages.success(request, 'محصول برای مقایسه کردن اضافه شد')
    return redirect(url)


def show_compare(request):
    if request.user.is_authenticated:
        data = Compare.objects.filter(user_id=request.user.id)
        return render(request, 'main/compare.html', {'data': data})
    else:
        data = Compare.objects.filter(session_key__exact=request.session.session_key, user_id=None)
        return render(request, 'main/compare.html', {'data': data})


class Compare_del(DeleteView):
    model = Compare
    success_url = reverse_lazy('main:show')
    template_name = 'main/compare_confirm_delete.html'

templates/main/category.html
{% extends 'main/base.html' %}
{% load static %}
{% load humanize %}
{% load ratings %}
{% load thumbnail %}
{% load base_tags %}
{% block main %}

    <!-- main-area -->
    <main>

        <!-- breadcrumb-area -->
        <section class="breadcrumb-area breadcrumb-bg" data-background="{% static 'main/img/bg/newsletter_bg.jpg' %}">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="breadcrumb-content">
                            <h2>لیست دسته بندی  {{ category.name }}</h2>
                            <nav aria-label="breadcrumb">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="{% url 'main:home' %}">خانه </a></li>
                                    <li class="breadcrumb-item active" aria-current="page">لیست دسته بندی  {{ category.name }}</li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- breadcrumb-area-end -->

        <!-- shop-area -->
        <section class="shop-area pt-95 pb-100">
            <div class="container">
                {#                <div class="shop-top-meta mb-35">#}
                {#                    <div class="row">#}
                {#                        <div class="col-md-6">#}
                {#                            <div class="shop-top-left">#}
                {#                                <ul>#}
                {#                                    <li><a href="#"><i class="flaticon-menu"></i> فیلتر </a></li>#}
                {#                                    <li>نمایش 1-9 از 80 نتیجه</li>#}
                {#                                </ul>#}
                {#                            </div>#}
                {#                        </div>#}
                {#                        <div class="col-md-6">#}
                {#                            <div class="shop-top-right">#}
                {#                                <form action="#">#}
                {#                                    <select name="select">#}
                {#                                        <option value="">مرتب سازی بر اساس جدید بودن</option>#}
                {#                                        <option>حمل رایگان</option>#}
                {#                                        <option>بهترین مسابقه</option>#}
                {#                                        <option>موارد جدید</option>#}
                {#                                        <option>اندازه A - Z</option>#}
                {#                                    </select>#}
                {#                                </form>#}
                {#                                <div class="shop-search"><a href="#"><i class="flaticon-search"></i></a></div>#}
                {#                            </div>#}
                {#                        </div>#}
                {#                    </div>#}
                {#                </div>#}
                {##}
                {##}
                <div class="row">
                    {% if category.products.published %}
                        {% for product in category.products.published %}
                            <div class="col-xl-3 col-lg-4 col-sm-6">
                                <div class="new-arrival-item text-center mb-50">
                                    <div class="thumb mb-25">
                                        {% if product.discount %}
                                            <div class="discount-tag">{{ product.discount }}% -</div>
                                        {% endif %}
                                        {% thumbnail product.image "500x550" crop="center" as img %}
                                            <a href="{{ product.get_absolute_url }}">
                                                <img src="{{ img.url }}" alt="">
                                            </a>
                                        {% endthumbnail %}
                                        <div class="product-overlay-action">
                                            <ul>
                                                {% if request.user.is_authenticated %}
                                                    {% if request.user in product.favourite.all %}
                                                        <li>
                                                            <a href="{% url 'main:favourite_product' product.id %}"
                                                               class="favourite-product fa-btn1" data-id='1'
                                                               data-text="remove"><i class="fa fa-heart test1"
                                                                                     style="color:red"></i></a>
                                                        </li>
                                                    {% else %}
                                                        <li>
                                                            <a href="{% url 'main:favourite_product' product.id %}"
                                                               class="favourite-product fa-btn2" data-id='2'
                                                               data-text="add">
                                                                <i class="fa fa-heart test2"
                                                                   style="color:#eee"></i></a>
                                                        </li>
                                                    {% endif %}
                                                {% else %}
                                                    <div data-toggle="tooltip" data-placement="right"
                                                         title="برای افزودن به علاقه مندیها باید وارد شوید">
                                                        <li>
                                                            <i class="fa fa-heart test2" style="color:#eee"></i>
                                                        </li>
                                                    </div>
                                                {% endif %}
                                                <li><a href="{{ product.get_absolute_url }}"><i
                                                        class="far fa-eye"></i></a>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                    <div class="content">
                                        <h5><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></h5>
                                        {% if not product.discount %}
                                            <p style="color: orangered"
                                               class="price">{{ product.unit_price|intcomma }}<span
                                                    style="color: orangered">  تومان  </span>
                                            </p>

                                        {% else %}
                                            <p class="price">
                                                <s style="color: #a7a6a6;">{{ product.unit_price|intcomma }}</s>
                                                &nbsp;&nbsp;
                                                <span style="color: orangered">{{ product.total_price | intcomma }}  تومان  </span>
                                            </p>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    {% else %}
                        <h3 style="margin: auto;">دسته بندی این مورد خالی است :(</h3>
                    {% endif %}
                </div>
            </div>
        </section>
        <!-- shop-area-end -->

    </main>
    <script>
        $(document).on('click', '.favourite-product', function (e) {
            e.preventDefault();
            var selector = $(this)
            var data_id = $(this).data("id")
            var likeText = $(this).data("text");
            var trim = $.trim(likeText)
            console.log(data_id + " " + likeText)
            $.ajax({
                url: $(this).attr('href'),
                type: 'GET',
                data: $(this).serialize(),
                dataType: 'json',
            });
            if (trim === 'add') {
                selector.find("i").css({
                    "color": "red"
                });
                selector.data("text", "remove")
            } else {
                selector.find("i").css({
                    "color": "#eee"
                });
                selector.data("text", "add")
            }
        });
    </script>
{% endblock %}

templates/main/shop.html
{% extends 'main/base.html' %}
{% load static %}
{% load humanize %}
{% load ratings %}
{% load thumbnail %}
{% load base_tags %}
{% block main %}

    <!-- main-area -->
    <main>

        <!-- breadcrumb-area -->
        <section class="breadcrumb-area breadcrumb-bg" data-background="{% static 'main/img/bg/breadcrumb_bg02.jpg' %}">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="breadcrumb-content">
                            <h2>لیست علاقه مندی ها</h2>
                            <nav aria-label="breadcrumb">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="{% url 'main:home' %}">خانه </a></li>
                                    <li class="breadcrumb-item active" aria-current="page">لیست علاقه مندی ها</li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- breadcrumb-area-end -->

        <!-- shop-area -->
        <section class="shop-area pt-95 pb-100">
            <div class="container">
                {#                <div class="shop-top-meta mb-35">#}
                {#                    <div class="row">#}
                {#                        <div class="col-md-6">#}
                {#                            <div class="shop-top-left">#}
                {#                                <ul>#}
                {#                                    <li><a href="#"><i class="flaticon-menu"></i> فیلتر </a></li>#}
                {#                                    <li>نمایش 1-9 از 80 نتیجه</li>#}
                {#                                </ul>#}
                {#                            </div>#}
                {#                        </div>#}
                {#                        <div class="col-md-6">#}
                {#                            <div class="shop-top-right">#}
                {#                                <form action="#">#}
                {#                                    <select name="select">#}
                {#                                        <option value="">مرتب سازی بر اساس جدید بودن</option>#}
                {#                                        <option>حمل رایگان</option>#}
                {#                                        <option>بهترین مسابقه</option>#}
                {#                                        <option>موارد جدید</option>#}
                {#                                        <option>اندازه A - Z</option>#}
                {#                                    </select>#}
                {#                                </form>#}
                {#                                <div class="shop-search"><a href="#"><i class="flaticon-search"></i></a></div>#}
                {#                            </div>#}
                {#                        </div>#}
                {#                    </div>#}
                {#                </div>#}
                {##}
                {##}
                <div class="row">
                    {% if product %}
                        {% for product in product %}
                            <div class="col-xl-3 col-lg-4 col-sm-6">
                                <div class="new-arrival-item text-center mb-50">
                                    <div class="thumb mb-25">
                                        {% if product.discount %}
                                            <div class="discount-tag">{{ product.discount }}% -</div>
                                        {% endif %}
                                        {% thumbnail product.image "500x550" crop="center" as img %}
                                            <a href="{{ product.get_absolute_url }}">
                                                <img src="{{ img.url }}" alt="">
                                            </a>
                                        {% endthumbnail %}
                                        <div class="product-overlay-action">
                                            <ul>
                                                {% if request.user.is_authenticated %}
                                                    {% if request.user in product.favourite.all %}
                                                        <li>
                                                            <a href="{% url 'main:favourite_product' product.id %}"
                                                               class="favourite-product fa-btn1" data-id='1'
                                                               data-text="remove"><i class="fa fa-heart test1"
                                                                                     style="color:red"></i></a>
                                                        </li>
                                                    {% else %}
                                                        <li>
                                                            <a href="{% url 'main:favourite_product' product.id %}"
                                                               class="favourite-product fa-btn2" data-id='2'
                                                               data-text="add">
                                                                <i class="fa fa-heart test2"
                                                                   style="color:#eee"></i></a>
                                                        </li>
                                                    {% endif %}
                                                {% else %}
                                                    <div data-toggle="tooltip" data-placement="right"
                                                         title="برای افزودن به علاقه مندیها باید وارد شوید">
                                                        <li>
                                                            <i class="fa fa-heart test2" style="color:#eee"></i>
                                                        </li>
                                                    </div>
                                                {% endif %}
                                                <li><a href="{{ product.get_absolute_url }}"><i
                                                        class="far fa-eye"></i></a>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                    <div class="content">
                                        <h5><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></h5>
                                        {% if not product.discount %}
                                            <p style="color: orangered"
                                               class="price">{{ product.unit_price|intcomma }}<span
                                                    style="color: orangered">  تومان  </span>
                                            </p>

                                        {% else %}
                                            <p class="price">
                                                <s style="color: #a7a6a6;">{{ product.unit_price|intcomma }}</s>
                                                &nbsp;&nbsp;
                                                <span style="color: orangered">{{ product.total_price | intcomma }}  تومان  </span>
                                            </p>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    {% else %}
                        <h3 style="margin: auto;">لیست علاقه مندی شما خالی است :(</h3>
                    {% endif %}
                </div>
            </div>
        </section>
        <!-- shop-area-end -->

    </main>
    <script>
        $(document).on('click', '.favourite-product', function (e) {
            e.preventDefault();
            var selector = $(this)
            var data_id = $(this).data("id")
            var likeText = $(this).data("text");
            var trim = $.trim(likeText)
            console.log(data_id + " " + likeText)
            $.ajax({
                url: $(this).attr('href'),
                type: 'GET',
                data: $(this).serialize(),
                dataType: 'json',
            });
            if (trim === 'add') {
                selector.find("i").css({
                    "color": "red"
                });
                selector.data("text", "remove")
            } else {
                selector.find("i").css({
                    "color": "#eee"
                });
                selector.data("text", "add")
            }
        });
    </script>
{% endblock %}