Internet_Market/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('', include('main.urls', namespace='home')),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),

]

cart/urls.py
from django.urls import path, re_path
from cart import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_details, name='details'),
    path('add/', views.cart_add, name='add'),
    path('remove/<int:id>/', views.cart_remove, name='remove'),
    # path('clear/', views.cart_remove_all, name='clear'),
    path('show/', views.cart_show, name='show'),
    path('add-single/', views.add_single, name='add-single'),
]

orders/urls.py
from django.urls import path, re_path
from orders import views

app_name = 'order'
urlpatterns = [
    # re_path('(?P<order_id>[-\w]*)/$', views.detail, name='detail'),
    path('<int:order_id>/', views.detail, name='detail'),
    path('create/', views.order_create, name='create'),
    path('information/', views.order_information, name='information'),
    path('apply/<int:order_id>/', views.CouponApplyView, name='apply_coupon'),
    path('request/<int:order_id>/', views.send_request, name='request'),
    path('verify/', views.verify, name='verify'),
]

orders/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from Internet_Market import settings
from main.models import Product, Variant
from iranian_cities.fields import OstanField, ShahrestanField
from django_jalali.db import models as jmodels


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='orders',verbose_name='خریدار')
    created = jmodels.jDateTimeField(auto_now_add=True)
    paid = models.BooleanField(default=False,verbose_name='خریده شده')
    first_name = models.CharField(max_length=100,verbose_name='نام')
    last_name = models.CharField(max_length=100,verbose_name='نام خانوادگی')
    address = models.TextField(blank=True, null=True,verbose_name='آدرس')
    ostan = OstanField(blank=True, null=True,verbose_name='استان')
    shahrestan = ShahrestanField(blank=True, null=True,verbose_name='شهرستان')
    postalcode = models.PositiveIntegerField(default=0,verbose_name='کد پستی')
    description = models.TextField(blank=True, null=True,verbose_name='توضیحات پست')
    email = models.EmailField(blank=True, null=True,verbose_name='ایمیل')
    discount = models.IntegerField(blank=True, null=True, default=None,verbose_name='تخفبف')
    code = models.CharField(max_length=200, null=True,verbose_name='کد سفارش')
    tracking_post = models.BigIntegerField(blank=True, null=True,verbose_name='کد رهگیری')

    # def jpublish(self):
    #     return jalali_converter(self.created)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return f'{self.user}-(str{self.id})'

    def get_total_price(self):
        total = sum(item.get_cost() for item in self.items.all())
        if self.discount:
            discount_price = (self.discount / 100) * total
            return int(total - discount_price)
        return total


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=True, null=True)
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items')
    variant = models.ForeignKey(Variant, on_delete=models.CASCADE, blank=True, null=True)
    price = models.IntegerField()
    quantity = models.PositiveIntegerField(default=0)

    def __str__(self):
        return f'str{self.id}'

    def size(self):
        return self.variant.size_variant.name

    def color(self):
        return self.variant.color_variant.name

    def get_cost(self):
        return self.price * self.quantity


class Coupon(models.Model):
    code = models.CharField(max_length=30, unique=True,verbose_name='کد تخفیف')
    valid_from = jmodels.jDateTimeField(verbose_name='از')
    valid_to = jmodels.jDateTimeField(verbose_name='تا')
    discount = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(90)],verbose_name='درصد تخفیف')
    active = models.BooleanField(default=False,verbose_name='وضعیت')

    def __str__(self):
        return self.code

orders/forms.py
from django import forms
from django.forms import ModelForm

from orders.models import Order


class CouponApplyForm(forms.Form):
    code = forms.CharField()
    

class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = ['first_name','last_name','address', 'ostan', 'shahrestan', 'postalcode', 'description','email']

orders/views.py
import datetime
import json

import jdatetime
import requests
from django.contrib import messages
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.utils.crypto import get_random_string
from cart.cart import Cart
from orders.forms import OrderForm, CouponApplyForm
from orders.models import Order, OrderItem, Coupon
from django.contrib.auth.decorators import login_required


@login_required()
def detail(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    form = CouponApplyForm()
    context = {'order': order, 'form': form}
    return render(request, 'orders/orders.html', context)


@login_required()
def order_information(request):
    form = OrderForm()
    user = request.user
    context = {'form': form, 'user': user}
    return render(request, 'orders/checkout.html', context)


@login_required()
def order_create(request):
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            code = get_random_string(length=8)
            order = Order.objects.create(user=request.user,
                                         first_name=data['first_name'],
                                         last_name=data['last_name'],
                                         address=data['address'],
                                         ostan=data['ostan'],
                                         shahrestan=data['shahrestan'],
                                         postalcode=data['postalcode'],
                                         description=data['description'],
                                         email=data['email'],
                                         code=code)
            cart = Cart(request)
            for item in cart:
                OrderItem.objects.create(order_id=order.id, user_id=request.user.id, variant=item['variant'],
                                         price=item['price'], quantity=item['quantity'])
                cart.clear()
            return redirect('order:detail', order.id)


def CouponApplyView(request, order_id):
    now = jdatetime.datetime.now()
    form = CouponApplyForm(request.POST)
    if form.is_valid():
        code = form.cleaned_data['code']
        try:
            coupon = Coupon.objects.get(code__exact=code, valid_from__lte=now, valid_to__gte=now, active=True)
        except Coupon.DoesNotExist:
            messages.error(request, 'این کد تخفیف وجود ندارد', 'danger')
            return redirect('order:detail', order_id)
        order = Order.objects.get(id=order_id)
        order.discount = coupon.discount
        order.save()
        messages.success(request, ' کد تخفیف با موفقیت اعمال شد', 'success')
    return redirect('order:detail', order_id, )


MERCHANT = ''
ZP_API_REQUEST = "https://api.zarinpal.com/pg/v4/payment/request.json"
ZP_API_VERIFY = "https://api.zarinpal.com/pg/v4/payment/verify.json"
ZP_API_STARTPAY = "https://www.zarinpal.com/pg/StartPay/{authority}"
amount = 11000  # Rial / Required
description = "توضیحات مربوط به تراکنش را در این قسمت وارد کنید"  # Required
email = 'email@example.com'  # Optional
mobile = '09123456789'  # Optional
# Important: need to edit for realy server.
CallbackURL = 'http://127.0.0.1:8000/order/verify/'


@login_required()
def send_request(request, order_id):
    global o_id
    o_id = order_id
    orders = get_object_or_404(Order, id=order_id)
    req_data = {
        "merchant_id": MERCHANT,
        "amount": orders.get_total_price(),
        "callback_url": CallbackURL,
        "description": description,
        "metadata": {"mobile": mobile, "email": email}
    }
    req_header = {"accept": "application/json",
                  "content-type": "application/json'"}
    req = requests.post(url=ZP_API_REQUEST, data=json.dumps(
        req_data), headers=req_header)
    authority = req.json()['data']
    if len(req.json()['errors']) == 0:
        return redirect(ZP_API_STARTPAY.format(authority=authority))
    else:
        e_code = req.json()['errors']['code']
        e_message = req.json()['errors']['message']
        return HttpResponse(f"Error code: {e_code}, Error Message: {e_message}")


@login_required()
def verify(request):
    order = get_object_or_404(Order, id=o_id)
    t_status = request.GET.get('Status')
    t_authority = request.GET['Authority']
    if request.GET.get('Status') == 'OK':
        req_header = {"accept": "application/json",
                      "content-type": "application/json'"}
        req_data = {
            "merchant_id": MERCHANT,
            "amount": order.get_total_price(),
            "authority": t_authority
        }
        req = requests.post(url=ZP_API_VERIFY, data=json.dumps(req_data), headers=req_header)
        if len(req.json()['errors']) == 0:
            t_status = req.json()['data']['code']
            if t_status == 100:
                order.paid = True
                order.save()
                return HttpResponse('Transaction success.\nRefID: ' + str(
                    req.json()['data']['ref_id']
                ))
            elif t_status == 101:
                return HttpResponse('Transaction submitted : ' + str(
                    req.json()['data']['message']
                ))
            else:
                return HttpResponse('Transaction failed.\nStatus: ' + str(
                    req.json()['data']['message']
                ))
        else:
            e_code = req.json()['errors']['code']
            e_message = req.json()['errors']['message']
            return HttpResponse(f"Error code: {e_code}, Error Message: {e_message}")
    else:
        return HttpResponse('Transaction failed or canceled by user')

templates/orders/checkout.html
{% extends 'main/base.html' %}
{% block main %}
    <main>

        {#            <!-- breadcrumb-area -->#}
        {#            <section class="breadcrumb-area breadcrumb-bg" data-background="img/bg/breadcrumb_bg03.jpg">#}
        {#                <div class="container">#}
        {#                    <div class="row">#}
        {#                        <div class="col-12">#}
        {#                            <div class="breadcrumb-content">#}
        {#                                <h2>صفحه پرداخت</h2>#}
        {#                                <nav aria-label="breadcrumb">#}
        {#                                    <ol class="breadcrumb">#}
        {#                                        <li class="breadcrumb-item"><a href="index.html">خانه </a></li>#}
        {#                                        <li class="breadcrumb-item active" aria-current="page">پرداخت </li>#}
        {#                                    </ol>#}
        {#                                </nav>#}
        {#                            </div>#}
        {#                        </div>#}
        {#                    </div>#}
        {#                </div>#}
        {#            </section>#}
        {#            <!-- breadcrumb-area-end -->#}

        <!-- checkout-area -->
        <section class="checkout-area pt-95 pb-95">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-7">
                        <div class="checkout-wrap">
                            <div class="checkout-top">
                                <h5 class="title">جزئیات سفارش</h5>
                                <a href="{% url 'cart:details' %}" class="back"><i class="fas fa-angle-left"></i> --
                                    بازگشت به سبد خرید</a>
                            </div>
                            <form action="{% url 'order:create' %}" class="checkout-form" method="post">{% csrf_token %}
                                <div class="row">
                                    <div class="col-sm-6">
                                        <div class="form-grp">
                                            <label for="">نام اصلی <span>*</span></label>
                                            <input type="text" name="first_name">
                                        </div>
                                    </div>
                                    <div class="col-sm-6">
                                        <div class="form-grp">
                                            <label for="">نام خانوادگی <span>*</span></label>
                                            <input type="text" name="last_name">
                                        </div>
                                    </div>

                                    <div class="col-sm-6">
                                        <div class="form-grp">
                                            <label>استان <span>*</span></label>
                                            <select name="ostan" id="id_ostan" required>
                                                <option value={{ form.ostan }}>

                                                </option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-sm-6">
                                        <div class="form-grp">
                                            <label>شهر شما <span>*</span></label>
                                             <select name="shahrestan" id="id_shahrestan" required>
                                                <option value={{ form.shahrestan }}>

                                                </option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-12">
                                        <div class="form-grp">
                                            <label for="address">آدرس خیابان <span>*</span></label>
                                            <input type="text" name="address" required>
                                        </div>
                                    </div>
                                    <div class="col-sm-6">
                                        <div class="form-grp">
                                            <label for="zip">کد پستی <span>*</span></label>
                                            <input type="text" name="postalcode" required>
                                        </div>
                                    </div>
                                    <div class="col-sm-6">
                                        <div class="form-grp">
                                            <label for="phone">شماره تلفن <span>*</span></label>
                                            <input type="text" name="mobile" value="{{ user.mobile }}" readonly>
                                        </div>
                                    </div>
                                    <div class="col-12">
                                        <div class="form-grp">
                                            <label for="email">آدرس ایمیل <span>(اختیاری)</span></label>
                                            <input type="email" name="email" value={{ user.email }}>
                                        </div>
                                    </div>
                                    <div class="col-12">
                                        <div class="different-address custom-control custom-checkbox">
                                            <input type="checkbox" class="custom-control-input" id="stda">
                                            <label class="custom-control-label" for="stda">به آدرس متفاوتی ارسال
                                                شود؟</label>
                                        </div>
                                    </div>
                                    <div class="col-12">
                                        <div class="form-grp mb-0">
                                            <label for="message">سفارش دهید که یادداشت داشته باشید
                                                <span>(اختیاری)</span></label>
                                            <textarea name="description" id="description"
                                                      placeholder="درباره یادداشت های ویژه تحویل شما"></textarea>
                                        </div>
                                    </div>
                                </div>
                                <button class="btn"> پروسه پرداخت</button>
                                {% csrf_token %}

                            </form>
                        </div>
                    </div>
                    {#                    <div class="col-lg-5 col-md-8">#}
                    {#                        <aside class="checkout-sidebar">#}
                    {#                            <h6 class="title">مجموع سبد خرید</h6>#}
                    {#                            <div class="shop-cart-widget">#}
                    {#                                <form action="{% url 'order:create' %}">#}
                    {#                                    <ul>#}
                    {#                                        <li class="sub-total"><span>کل خرید </span> 136000 تومان</li>#}
                    {#                                        <li>#}
                    {#                                            <span>حمل و نقل</span>#}
                    {#                                            <div class="shop-check-wrap">#}
                    {#                                                <div class="custom-control custom-checkbox">#}
                    {#                                                    <input type="checkbox" class="custom-control-input"#}
                    {#                                                           id="customCheck1">#}
                    {#                                                    <label class="custom-control-label" for="customCheck1">نرخ مسطح:#}
                    {#                                                        15000 تومان</label>#}
                    {#                                                </div>#}
                    {#                                                <div class="custom-control custom-checkbox">#}
                    {#                                                    <input type="checkbox" class="custom-control-input"#}
                    {#                                                           id="customCheck2">#}
                    {#                                                    <label class="custom-control-label" for="customCheck2">حمل#}
                    {#                                                        رایگان</label>#}
                    {#                                                </div>#}
                    {#                                                <a href="#" class="calculate">حمل و نقل را محاسبه کنید</a>#}
                    {#                                            </div>#}
                    {#                                        </li>#}
                    {#                                        <li class="cart-total-amount"><span>مجموع </span> <span class="amount">151000 تومان</span>#}
                    {#                                        </li>#}
                    {#                                    </ul>#}
                    {#                                    <div class="payment-method-info">#}
                    {#                                        <div class="paypal-method-flex">#}
                    {#                                            <div class="custom-control custom-checkbox">#}
                    {#                                                <input type="checkbox" class="custom-control-input" id="customCheck5">#}
                    {#                                                <label class="custom-control-label" for="customCheck5">پرداخت نقدی هنگام#}
                    {#                                                    تحویل</label>#}
                    {#                                                <p>هنگام تحویل با پرداخت نقدی پرداخت کنید.</p>#}
                    {#                                            </div>#}
                    {#                                        </div>#}
                    {#                                        <div class="paypal-method-flex">#}
                    {#                                            <div class="custom-control custom-checkbox">#}
                    {#                                                <input type="checkbox" class="custom-control-input" id="customCheck6">#}
                    {#                                                <label class="custom-control-label" for="customCheck6">پرداخت در#}
                    {#                                                    کارت</label>#}
                    {#                                            </div>#}
                    {#                                            <div class="paypal-logo"><img src="img/images/card.png" alt=""></div>#}
                    {#                                        </div>#}
                    {#                                    </div>#}
                    {#                                    <div class="payment-terms">#}
                    {#                                        <p>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از#}
                    {#                                            طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که#}
                    {#                                            لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود#}
                    {#                                            ابزارهای کاربردی می باشد. </p>#}
                    {#                                        <div class="custom-control custom-checkbox">#}
                    {#                                            <input type="checkbox" class="custom-control-input" id="customCheck7">#}
                    {#                                            <label class="custom-control-label" for="customCheck7">من شرایط وب سایت را#}
                    {#                                                خوانده و با آنها موافقم</label>#}
                    {#                                        </div>#}
                    {#                                    </div>#}
                    {#                                    <button class="btn"> پروسه پرداخت</button>#}
                    {#                                </form>#}
                    {#                            </div>#}
                    {#                        </aside>#}
                    {#                    </div>#}
                </div>
            </div>
        </section>
        <!-- checkout-area-end -->

    </main>
    <!-- main-area-end -->


{% endblock %}

templates/orders/orders.html
{% extends 'main/base.html' %}
{% load static %}
{% load humanize %}
{% block main %}

    <!-- main-area -->
    <main>

        <!-- breadcrumb-area -->
        {#        <section class="breadcrumb-area breadcrumb-bg" data-background="img/bg/breadcrumb_bg03.jpg">#}
        {#            <div class="container">#}
        {#                <div class="row">#}
        {#                    <div class="col-12">#}
        {#                        <div class="breadcrumb-content">#}
        {#                            <h2>صفحه سبد خرید</h2>#}
        {##}
        {#                        </div>#}
        {#                    </div>#}
        {#                </div>#}
        {#            </div>#}
        {#        </section>#}
        <!-- breadcrumb-area-end -->

        <!-- cart-area -->
        <div class="cart-area pt-100 pb-100">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="cart-wrapper">

                            <div class="cart-total pt-95">
                                <h3 class="title">مجموع سبد خرید</h3>
                                <div class="shop-cart-widget">
                                    <form action="#">
                                        <ul>

                                            {##}
                                            {#                                            <li>قیمت واحد : &emsp;&ensp;&emsp;&ensp;<span#}
                                            {#                                                    id="price">تومان{{ order_item.price}}</span></li>#}
                                            {#                                        <li>تعداد :&emsp;&ensp;&emsp;&ensp;&emsp;&ensp;&emsp;&emsp;&ensp;<span#}
                                            {#                                                id="quantity">{{ order.quantity }}</span></li>#}
                                            {% if order.discount %}
                                                <li>تخفیف :&emsp;&ensp;&emsp;&ensp;&emsp;&ensp;&emsp;&ensp;<span
                                                        id="discount">{{ order.discount }}%</span></li>
                                            {% else %}
                                                <empty></empty>
                                            {% endif %}
                                            <li class="cart-total-amount"><span>مجموع </span> <span
                                                    class="amount">{{ order.get_total_price|intcomma }} تومان</span>
                                            </li>
                                        </ul>

                                    </form>

                                </div>
                            </div>
                            {% if messages %}
                                <ul class="messages">
                                    {% for message in messages %}
                                        {% if message.tags %}

                                            <div class="alert alert-success" role="alert">
                                                <button type="button" class="close"
                                                        data-dismiss="alert" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>&nbsp;&nbsp;
                                                {{ message }}

                                            </div>

                                        {% endif %}
                                    {% endfor %}
                                </ul>
                            {% endif %}
                            <div class="shop-cart-bottom mt-20">
                                <div class="cart-coupon">
                                    <form action="{% url 'order:apply_coupon' order.id %}"
                                          method="post">{% csrf_token %}
                                        {{ form.as_p }}
                                        <button class="btn">اعمال کد</button>
                                    </form>
                                </div>
                                <div class="continue-shopping">
                                    {#                                    <a href="shop.html" class="btn">بروز خرید </a>#}
                                    <a href="{% url 'order:request' order.id %}" class="btn">پروسه پرداخت </a>

                                </div>

                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
        <!-- cart-area-end -->

    </main>

{% endblock %}